title: Machine Learning Camp Jeju
description: Enjoy, Share, Grow
github: [metadata]
google_analytics: UA-112439062-1
baseurl: /mlcampjeju

theme: jekyll-theme-cayman
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - README.md
